# permissions for end users to view configmapwatchers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: configmapwatcher-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: configmap
    app.kubernetes.io/part-of: configmap
    app.kubernetes.io/managed-by: kustomize
  name: configmapwatcher-viewer-role
rules:
- apiGroups:
  - configmap.xinyu.com
  resources:
  - configmapwatchers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - configmap.xinyu.com
  resources:
  - configmapwatchers/status
  verbs:
  - get
